services:
  bud-e:
    image: denoland/deno:latest
    container_name: bud-e
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/bud-e
    command: sh -c "apt-get update && apt-get install -y git && git config --global --add safe.directory /bud-e && cd /bud-e && (git rev-parse --git-dir || git init) && if [ -d '.git' ]; then git remote add origin https://github.com/LAION-AI/bud-e.git || true && git fetch origin && git checkout -B main origin/main; else git clone -b main https://github.com/LAION-AI/bud-e.git .; fi && deno task build && deno task preview"
    networks:
      - app-network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
